### ISSUE TITLE
SNPs points can not fill the whole plot (I am plotting rice not human data)

### ISSUE THREAD

**Issue by qj009** [totajuliusd/topr#26]
Hello, I am plotting rice data and data points can not fill the whole plot. It contains a big empty gap between chromsomes. When I plot one chromsome, it looks ok. But It does not show legend for multiple phenotypes.

**Comment by totajuliusd** [comment]
Hi, this is most likely because you are plotting rice data. The manhattan plot assumes there are 22 or 23 chromosomes of a certain length in the input datasets.  

This however does not explain why it doesnt show a legend for multiple phenotypes. Can you please show me the command you are using to call the manhattan plot function and a screenshot of your plot?

**Comment by qj009** [comment]
Hi, it can plot 12 chrosome. It just contain big gap between chrosomes, like the picture attached below. 
The code is: `manhattan(list(hap_plot, hapi_plot,snp), legend_labels = c("pheno1", "pheno2","pheno3"),sign_thresh = 5e-06)`
<img width="1266" alt="Screen Shot 2023-09-07 at 9 35 27 AM" src="https://github.com/totajuliusd/topr/assets/57466652/ff2337e2-9734-44c2-ae2e-68647dfbcd84">

Besides, it can not show the legend when I only plot one chromsome. And one chromsome plot looks ok to me since it can fill the whole plot. 
code: `manhattan(list(hap_plot, hapi_plot,snp), legend_labels = c("pheno1", "pheno2","pheno3"),sign_thresh = 5e-06)`

<img width="763" alt="Screen Shot 2023-09-07 at 9 39 24 AM" src="https://github.com/totajuliusd/topr/assets/57466652/b580c54d-3aa3-4c49-8ccb-7ca95b8ed36d">

**Comment by totajuliusd** [comment]
The gaps on the Manhattan plots are there because the human chromosomes are larger than the rice chromosomes. There is a relatively easy fix to this which I will implement in topr version 1.1.10.

The missing legend when plotting one chromosome only, is a bug introduced in version 1.1.9. This will be fixed in version 1.1.10 as well. Until then, you can add the **use_shades** argument as a temporary fix:

manhattan(list(hap_plot, hapi_plot,snp), legend_labels = c("pheno1", "pheno2","pheno3"),sign_thresh = 5e-06, chr="chr12", **use_shades=T**)

 I will let you know when version 1.1.10 is released - it should be within the next couple of days, or at the weekend.

**Comment by totajuliusd** [comment]
Hi again,

topr_v.1.1.10 is now available from CRAN. Now you can make Manhattan plots from datasets with varying number of chromosomes and chromosome lengths by including the argument **get_chr_lengths_from_data = T** in your manhattan function call. 

Example:
`> manhattan(CD_UKBB %>% filter(POS < 80000000))`

![image](https://github.com/totajuliusd/topr/assets/106526694/49f978d5-ddb3-4d6b-a12c-853d237c792e)

Example of how to plot without the gaps: 
`> manhattan(CD_UKBB %>% filter(POS < 80000000),  get_chr_lengths_from_data = T)`

![image](https://github.com/totajuliusd/topr/assets/106526694/ea7306b9-cb4f-4b37-bc35-2028f473c0dd)

Please let me know if something doesnt work as expected!

**Comment by qj009** [comment]
Hello, it works perfectly! Thank you!
