### ISSUE TITLE
Annotation source

### ISSUE THREAD

**Issue by shudanhua** [totajuliusd/topr#29]
Hi, 

Thank you for this nice package. 

I'm wondering if it is possible to use custom annotation data?
One of my target gene is CDC42, while it showed ENSG00000289694 in the plot. It will be great if I can change it into the gene name. Thank you in advance.

Danhua

**Comment by totajuliusd** [comment]
Hi Danhua and thank you for kind words. 

If the input dataset already includes gene information (in a column called gene, Gene_Symbol, or Gene_name), topr should use that for labelling instead.  If not there are other ways to solve this. 

But I wonder why you are seeing ENSG00000289694 instead of CDC42 though....

Can you please make a regionplot using the command below(just replace UC_UKBB with your data) and take a screenshot of the plot and show me? 

`regionplot(UC_UKBB, gene="CDC42", unit_ratios = "1:4.24:5",label_size = 3, annotate=1e-03, annotate_with = "Gene_Symbol").

When I make this regionplot I do not see the ENSG00000289694 gene:

![image](https://github.com/totajuliusd/topr/assets/106526694/e70d9ff2-cdea-4c4b-95bb-b8ecfa5e37f8)

Tota
`

**Comment by shudanhua** [comment]
Thank you so much Tota ! 

Problem solved with your help.
It was happened in the Manhattan plot, seems the annotation for my leader SNP is not as I expected. I changed the annotation column name in my data for topr to read.
The region plot works quite well, and same with yours..

Cheers,
Danhua
