### ISSUE TITLE
Change color of datasets in Manhattan/region plot

### ISSUE THREAD

**Issue by zara03** [totajuliusd/topr#63]
I am new to these analysis and want to make region plot but its not giving me colors of legend labels, like i want Cirrhosis to be green, Asthma to be red and Fibrosis to be brown. 

region_list <- list("Cirrhosis", "Asthma", "Fibrosis")
regionplot(region_list, gene = "IFIH1", size = 3, xmin = 132267974, xmax = 132318684,
           shape = c(1, 2, 3),
           legend_labels = c("Cirrhosis", "Asthma", "Fibrosis"),
           color = c("green", "red", "brown"),
           region_size = "2MB", legend_position = "right")

It is generating with default colors but not colors i want.
How to do so?

**Comment by zara03** [comment]
[help.pdf](https://github.com/totajuliusd/topr/files/14954232/help.pdf)

i want to make this kind of plot.

**Comment by totajuliusd** [comment]
See https://totajuliusd.github.io/topr_manual/regionplot.html for basic usage of the `regionplot` function. 

You have to provide the region you want to display using EITHER  the `gene` argument or the `region` argument. Or alternatively, you can provide the region with the `chr, xmin` and `xmax` arguments, but then you have to provide all 3 arguments.

So in your case this would be:

`regionplot(yourdata,  gene="IFIH1", ...)`

or 

`regionplot(yourdata, region="chr18:132267974-132318684", ... `

or

`regionplot(youdata, chr="chr18", xmin = 132267974, xmax = 132318684,... `

Also, why are your dataframe names within quotes in the following: 

`region_list <- list("Cirrhosis", "Asthma", "Fibrosis")`

And finally, what does the plot look like if you use the inbuild test data instead of your own, for example if you do:

`regionplot(list(CD_UKBB,CD_FINNGEN,UC_UKBB), gene="IL23R", size=3,shape = c(1, 2, 3), legend_labels = c("Cirrhosis", "Asthma", "Fibrosis"), color = c("green", "red", "brown"))`

**Comment by zara03** [comment]
thank you so much, the last code worked.
Another thing how we adjust shape to be empty like circle but not filled, only outline?

**Comment by totajuliusd** [comment]
Just like you have already done, by using the` shape=1 `argument, e.g.

`regionplot(CD_UKBB, gene="IL23R", shape=1)`
