### ISSUE TITLE
locuszoom issues

### ISSUE THREAD

**Issue by mvab** [totajuliusd/topr#64]
Hi, 

Thanks for this great package! Really good to see you're continuing to work on it.

I have a few small issues to report in locuszoom.

1) It seems that the annotate= flag does not work

`locuszoom(dat, build = 37, protein_coding_only = T, annotate=5e-8)`

<img width="673" alt="Screenshot 2024-04-17 at 17 03 02" src="https://github.com/totajuliusd/topr/assets/16936674/14b03fda-28c0-4706-b9d3-e309a70ebc8b">

2) However, when I tell it to add vline at that position, the label appers:

l`ocuszoom(ldat, build = 37, protein_coding_only = T, annotate=5e-8,
          rsids_with_vline = "rs186430430")`

<img width="498" alt="Screenshot 2024-04-17 at 17 08 25" src="https://github.com/totajuliusd/topr/assets/16936674/f810d853-ea6c-4680-9817-2c734263e623">

3) Next, the vline customization seems to only work on the bottom panel: 

`locuszoom(dat, build = 37, protein_coding_only = T, annotate=5e-8,
          rsids_with_vline = "rs186430430", vline_color = "blue", vline_size = 1)`

<img width="510" alt="Screenshot 2024-04-17 at 17 10 20" src="https://github.com/totajuliusd/topr/assets/16936674/39732880-380e-46ee-a855-d1062ebec708">

4) Also, do you have any advice for removing the letter 'a' in the legend?

I'm running topr v2.0.1, ggplot2 3.4.4, R 4.3.2

Many thanks

**Comment by totajuliusd** [comment]
Hi and thank you for your message. 

**- It seems that the annotate= flag does not work**

The reason why the annotation argument doesnt seem to be working is because the default **region_size** is set to 1000000 - meaning that only the top snp below the threshold provided by the annotate argument within the 1 MB window will be annotated. So to show the annotation for more snps, you have to reduce the region/window size like this:

`locuszoom(dat, build = 37, protein_coding_only = T, annotate=5e-8, region_size=100)`

If you set **region_size=1**,  then all the snps below the annotate threshold should be labelled.

**1. However, when I tell it to add vline at that position, the label appers:**

This is because the region_size argument is ignored when you label the snps by their rsids.

**1. Next, the vline customization seems to only work on the bottom panel:**

Thank you for brining this to my attention. I will fix this in the next topr release, which I aim to release at the end of this month.

**1. Also, do you have any advice for removing the letter 'a' in the legend?**

This is a problem I was aware of and aim to fix in the next topr release as well.

**Comment by totajuliusd** [comment]
Hi, this has been fixed in topr v. 2.0.2 which has been uploaded to CRAN
